/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteConfig = {
  _id: string;
  _type: "siteConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  causeTitle: string;
  causeBlurb: string;
  fundMessage: string;
  minimumIncrement: number;
  creatorName?: string;
  creatorPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  creatorBlurb?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type CycleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cycle";
};

export type LeaderboardEntry = {
  _id: string;
  _type: "leaderboardEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  displayName: string;
  companyName?: string;
  slug: Slug;
  url: string;
  tagline?: string;
  category: CategoryReference;
  cycle: CycleReference;
  amount: number;
  clickCount?: number;
  raiseCount?: number;
  razorpayOrderId?: string;
  razorpayPaymentId?: string;
  status: "pending" | "confirmed" | "failed";
  confirmedAt?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Cycle = {
  _id: string;
  _type: "cycle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  startDate: string;
  endDate: string;
  isActive?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SiteConfig
  | SanityImageCrop
  | SanityImageHotspot
  | CategoryReference
  | CycleReference
  | LeaderboardEntry
  | Slug
  | Cycle
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../app/api/click/[id]/route.ts
// Variable: ENTRY_URL_QUERY
// Query: *[_type == "leaderboardEntry" && _id == $id][0].url
export type ENTRY_URL_QUERY_RESULT = string | null;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: ACTIVE_CYCLE_QUERY
// Query: *[_type == "cycle" && isActive == true][0] {    _id,    title,    startDate,    endDate,    isActive  }
export type ACTIVE_CYCLE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  startDate: string;
  endDate: string;
  isActive: true;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: SITE_CONFIG_QUERY
// Query: *[_id == "siteConfig"][0] {    _id,    causeTitle,    causeBlurb,    fundMessage,    minimumIncrement,    creatorName,    "creatorPhotoUrl": creatorPhoto.asset->url,    creatorBlurb  }
export type SITE_CONFIG_QUERY_RESULT =
  | {
      _id: "siteConfig";
      causeTitle: null;
      causeBlurb: null;
      fundMessage: null;
      minimumIncrement: null;
      creatorName: null;
      creatorPhotoUrl: null;
      creatorBlurb: null;
    }
  | {
      _id: "siteConfig";
      causeTitle: string;
      causeBlurb: string;
      fundMessage: string;
      minimumIncrement: number;
      creatorName: string | null;
      creatorPhotoUrl: string | null;
      creatorBlurb: string | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: CONFIRMED_ENTRIES_QUERY
// Query: *[_type == "leaderboardEntry" && status == "confirmed" && cycle._ref == $cycleId]  | order(amount desc) {    _id,    "slug": slug.current,    displayName,    companyName,    tagline,    url,    amount,    clickCount,    "confirmedAt": coalesce(confirmedAt, _createdAt),    "category": category->{ _id, title, "slug": slug.current }  }
export type CONFIRMED_ENTRIES_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  displayName: string;
  companyName: string | null;
  tagline: string | null;
  url: string;
  amount: number;
  clickCount: number | null;
  confirmedAt: string;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
}>;

// Source: ../sanity/lib/queries.ts
// Variable: ENTRY_DETAIL_QUERY
// Query: *[_type == "leaderboardEntry" && status == "confirmed" && slug.current == $slug][0] {    _id,    "slug": slug.current,    displayName,    companyName,    tagline,    url,    amount,    clickCount,    raiseCount,    "confirmedAt": coalesce(confirmedAt, _createdAt),    "category": category->{ _id, title, "slug": slug.current },    "cycle": cycle->{ _id, title, startDate, endDate, isActive },    "categoryRank": 1 + count(*[      _type == "leaderboardEntry" && status == "confirmed" &&      cycle._ref == ^.cycle._ref && category._ref == ^.category._ref &&      amount > ^.amount    ]),    "categoryTotal": count(*[      _type == "leaderboardEntry" && status == "confirmed" &&      cycle._ref == ^.cycle._ref && category._ref == ^.category._ref    ]),    "overallRank": 1 + count(*[      _type == "leaderboardEntry" && status == "confirmed" &&      cycle._ref == ^.cycle._ref && amount > ^.amount    ]),    "overallTotal": count(*[      _type == "leaderboardEntry" && status == "confirmed" &&      cycle._ref == ^.cycle._ref    ]),    "siblings": *[      _type == "leaderboardEntry" && status == "confirmed" &&      cycle._ref == ^.cycle._ref && category._ref == ^.category._ref &&      _id != ^._id    ] | order(amount desc) [0...4] {      _id,      "slug": slug.current,      displayName,      companyName,      amount,      "rank": 1 + count(*[        _type == "leaderboardEntry" && status == "confirmed" &&        cycle._ref == ^.cycle._ref && category._ref == ^.category._ref &&        amount > ^.amount      ])    }  }
export type ENTRY_DETAIL_QUERY_RESULT = {
  _id: string;
  slug: string;
  displayName: string;
  companyName: string | null;
  tagline: string | null;
  url: string;
  amount: number;
  clickCount: number | null;
  raiseCount: number | null;
  confirmedAt: string;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  cycle: {
    _id: string;
    title: string | null;
    startDate: string;
    endDate: string;
    isActive: boolean | null;
  };
  categoryRank: number;
  categoryTotal: number;
  overallRank: number;
  overallTotal: number;
  siblings: Array<{
    _id: string;
    slug: string;
    displayName: string;
    companyName: string | null;
    amount: number;
    rank: number;
  }>;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: SCOPE_RANK_PREVIEW_QUERY
// Query: {    "rank": 1 + count(*[      _type == "leaderboardEntry" && status == "confirmed" &&      cycle._ref == $cycleId &&      ($categorySlug == null || category->slug.current == $categorySlug) &&      ($since == null || confirmedAt >= $since) &&      amount > $amount    ]),    "total": 1 + count(*[      _type == "leaderboardEntry" && status == "confirmed" &&      cycle._ref == $cycleId &&      ($categorySlug == null || category->slug.current == $categorySlug) &&      ($since == null || confirmedAt >= $since)    ])  }
export type SCOPE_RANK_PREVIEW_QUERY_RESULT = {
  rank: number;
  total: number;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "leaderboardEntry" && _id == $id][0].url': ENTRY_URL_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "cycle" && isActive == true][0] {\n    _id,\n    title,\n    startDate,\n    endDate,\n    isActive\n  }\n': ACTIVE_CYCLE_QUERY_RESULT;
    '\n  *[_id == "siteConfig"][0] {\n    _id,\n    causeTitle,\n    causeBlurb,\n    fundMessage,\n    minimumIncrement,\n    creatorName,\n    "creatorPhotoUrl": creatorPhoto.asset->url,\n    creatorBlurb\n  }\n': SITE_CONFIG_QUERY_RESULT;
    '\n  *[_type == "leaderboardEntry" && status == "confirmed" && cycle._ref == $cycleId]\n  | order(amount desc) {\n    _id,\n    "slug": slug.current,\n    displayName,\n    companyName,\n    tagline,\n    url,\n    amount,\n    clickCount,\n    "confirmedAt": coalesce(confirmedAt, _createdAt),\n    "category": category->{ _id, title, "slug": slug.current }\n  }\n': CONFIRMED_ENTRIES_QUERY_RESULT;
    '\n  *[_type == "leaderboardEntry" && status == "confirmed" && slug.current == $slug][0] {\n    _id,\n    "slug": slug.current,\n    displayName,\n    companyName,\n    tagline,\n    url,\n    amount,\n    clickCount,\n    raiseCount,\n    "confirmedAt": coalesce(confirmedAt, _createdAt),\n    "category": category->{ _id, title, "slug": slug.current },\n    "cycle": cycle->{ _id, title, startDate, endDate, isActive },\n    "categoryRank": 1 + count(*[\n      _type == "leaderboardEntry" && status == "confirmed" &&\n      cycle._ref == ^.cycle._ref && category._ref == ^.category._ref &&\n      amount > ^.amount\n    ]),\n    "categoryTotal": count(*[\n      _type == "leaderboardEntry" && status == "confirmed" &&\n      cycle._ref == ^.cycle._ref && category._ref == ^.category._ref\n    ]),\n    "overallRank": 1 + count(*[\n      _type == "leaderboardEntry" && status == "confirmed" &&\n      cycle._ref == ^.cycle._ref && amount > ^.amount\n    ]),\n    "overallTotal": count(*[\n      _type == "leaderboardEntry" && status == "confirmed" &&\n      cycle._ref == ^.cycle._ref\n    ]),\n    "siblings": *[\n      _type == "leaderboardEntry" && status == "confirmed" &&\n      cycle._ref == ^.cycle._ref && category._ref == ^.category._ref &&\n      _id != ^._id\n    ] | order(amount desc) [0...4] {\n      _id,\n      "slug": slug.current,\n      displayName,\n      companyName,\n      amount,\n      "rank": 1 + count(*[\n        _type == "leaderboardEntry" && status == "confirmed" &&\n        cycle._ref == ^.cycle._ref && category._ref == ^.category._ref &&\n        amount > ^.amount\n      ])\n    }\n  }\n': ENTRY_DETAIL_QUERY_RESULT;
    '\n  {\n    "rank": 1 + count(*[\n      _type == "leaderboardEntry" && status == "confirmed" &&\n      cycle._ref == $cycleId &&\n      ($categorySlug == null || category->slug.current == $categorySlug) &&\n      ($since == null || confirmedAt >= $since) &&\n      amount > $amount\n    ]),\n    "total": 1 + count(*[\n      _type == "leaderboardEntry" && status == "confirmed" &&\n      cycle._ref == $cycleId &&\n      ($categorySlug == null || category->slug.current == $categorySlug) &&\n      ($since == null || confirmedAt >= $since)\n    ])\n  }\n': SCOPE_RANK_PREVIEW_QUERY_RESULT;
  }
}
